# Generated by Django 4.0.3 on 2022-10-16 20:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rh.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, null=b'I00\n', verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Personal')),
                ('is_postulante', models.BooleanField(default=False, verbose_name='Postulante')),
                ('foto', models.ImageField(default='uploads/perfiles/log/personal.png', null=b'I01\n', upload_to='uploads/perfiles/update/', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': ' Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Analitica',
            fields=[
                ('id_analitica', models.CharField(help_text='Es el codigo homologado enviado por Revergy España', max_length=30, primary_key=b'I01\n', serialize=False, verbose_name='Analitica')),
                ('proyecto', models.CharField(help_text='Nombre del lugar donde reside el proyecto', max_length=70, verbose_name='Proyecto')),
                ('cliente', models.CharField(help_text='Nombre del cliente a realizar los servicios', max_length=30)),
                ('descripcion', models.TextField(default='', max_length=100)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', help_text='Estado actual del proyecto, si es alta omitir este campo', max_length=15)),
            ],
            options={
                'verbose_name': 'Analitica',
                'verbose_name_plural': ' Analiticas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo departamento')),
                ('area', models.CharField(choices=[('OPERACION Y MANTENIMIENTO', 'OPERACION Y MANTENIMIENTO'), ('COMERCIAL', 'COMERCIAL'), ('DIRECCION', 'DIRECCION'), ('O&S', 'O&S'), ('EHSQ', 'EHSQ'), ('GESTION VEHICULAR', 'GESTION VEHICULAR'), ('GESTION DE ACCESOS', 'GESTION DE ACCESOS'), ('RRHH', 'RRHH'), ('GESTION DE ALMACEN', 'GESTION DE ALMACEN'), ('COMPRAS Y LOGISTICA', 'COMPRAS Y LOGISTICA'), ('CONTROLLER', 'CONTROLLER'), ('FINANCIERO', 'FINANCIERO'), ('FORMACIONES', 'FORMACIONES'), ('TI', 'TI')], default='OPERACIÓN Y MANTENIMIENTO', max_length=50, verbose_name='Area')),
                ('proceso', models.CharField(choices=[('ESTRATEGICO', 'ESTRATEGICO'), ('OPERATIVO', 'OPERATIVO'), ('APOYO', 'APOYO')], default='OPERATIVO', max_length=60, verbose_name='Proceso')),
                ('departamento', models.CharField(max_length=60)),
                ('responsable', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now=True)),
                ('estatus', models.CharField(default='Asignado', max_length=30)),
                ('categoria', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rh.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=30, null=b'I01\n')),
                ('descripcion', models.CharField(max_length=30, null=b'I01\n')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('fk_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('perfil', models.CharField(help_text='Ingrese su perfil de especializacion', max_length=60, verbose_name='Perfil profesional')),
                ('correo', models.EmailField(max_length=60, verbose_name='Correo de contacto')),
                ('cv', models.FileField(help_text='Adjunte su Curruculum', upload_to=rh.models.upload_cv, verbose_name='CV')),
                ('ine', models.FileField(help_text='Adjunte su Identificacion personal(INE)', null=True, upload_to=rh.models.upload_ine, verbose_name='INE')),
                ('licencia', models.FileField(help_text='Adjunte su Licencia de manejo', null=True, upload_to=rh.models.upload_licencia, verbose_name='LICENCIA DE CONDUCIR')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Union libre', 'Union libre')], max_length=20, verbose_name='Estado civil')),
                ('edad', models.IntegerField(default=18, verbose_name='Edad')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono personal')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': ' Postulantes',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id_vacante', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(default='', max_length=100)),
                ('tarjeta', models.ImageField(default='cards/ofertas/procesos/operativo.png', max_length=255, upload_to='cards/ofertas/procesos/')),
                ('is_new', models.BooleanField(default=True)),
                ('is_prioridad', models.BooleanField(default=False, verbose_name='Es prioridad ?')),
                ('is_top', models.BooleanField(default=False, verbose_name='Desea destacar esta oferta?')),
                ('descripcion', models.TextField(help_text='Breve descipcion de las funciones, obligacions, y fundamentos de la oferta')),
                ('formacion', models.TextField(default='', help_text='Informacion academica requerida (Titulos, Certificados, Cursos, etc)', null=True)),
                ('experiencia', models.TextField(default='', help_text='Experiencia laboral requerida (Conocimientos Tecnicos, antecendetes en algun trabajo o empresa, etc)', null=True)),
                ('salario', models.CharField(default='', max_length=100, null=True, verbose_name='Salario bruto')),
                ('jornada', models.CharField(default='Tiempo completo', max_length=100, verbose_name='Tipo de jornada laboral')),
                ('tipo_contrato', models.CharField(default='', max_length=100, null=True, verbose_name='Tipo de contrato')),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fk_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.puesto', verbose_name='Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Question_rh',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.CharField(default='', max_length=80, verbose_name='¿Por qué te interesa trabajar en esta empresa?')),
                ('q2', models.CharField(default='', max_length=200, verbose_name='¿Qué sabes de nuestra empresa?')),
                ('q3', models.CharField(default='', max_length=200, verbose_name='¿Cuál es tu meta personal?')),
                ('q4', models.CharField(default='', max_length=200, verbose_name='¿Cuál es tu meta laboral?')),
                ('q5', models.CharField(default='', max_length=80, verbose_name='¿Cuál fue su última percepción neto mensual?')),
                ('q6', models.CharField(default='', max_length=200, verbose_name='Describe tus fortalezas o aptitudes')),
                ('q7', models.CharField(default='', max_length=200, verbose_name='Cuales considera que sean sus debilidades')),
                ('q8', models.CharField(default='', max_length=200, verbose_name='¿Qué te gusta hacer en tu tiempo libre?')),
                ('q9', models.CharField(default='', max_length=20, verbose_name='¿Actualmente trabajas?')),
                ('q10', models.CharField(default='', max_length=200, verbose_name='¿Qué funciones y responsabilidades has tenido en tus trabajos?')),
                ('q11', models.CharField(default='', max_length=80, verbose_name='¿Qué tipo de informes has realizado?')),
                ('q12', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=10, verbose_name='Del 1 al 10 ¿tu habilidad en Excel es?')),
                ('q13', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=10, verbose_name='¿Has realizado control de costes?')),
                ('q14', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='', max_length=10, verbose_name='¿Sabes realizar Informes semanales y Mensuales?')),
                ('q15', models.CharField(default='', max_length=80, verbose_name='¿Has trabajado en el extranjero? ¿En dónde?')),
                ('q16', models.CharField(default='', max_length=80, verbose_name='¿Cuál es el área o departamento al que deseas postular?')),
                ('aceptar_terminos', models.BooleanField(default=True, help_text='. Acepte los terminos y condiciones establecidas en la declaracion de Revergy Mexico para el tratamiento de todo la informacion proporcionada.', verbose_name='Aceptar Terminos Condiciones y privacidad de informacion')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('entrevista', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.entrevista')),
            ],
        ),
        migrations.CreateModel(
            name='Question_psicologico',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.CharField(default='', max_length=100, verbose_name='Mencione algunos datos personales tales como sus intereses en su adolescencia, la profesión o empleo de sus padres y qué influencia tuvieron sus experiencias familiares en su desarrollo')),
                ('q2', models.CharField(default='', max_length=100, verbose_name='¿Qué influencia tuvo su niñez en la clase de persona que es hoy?')),
                ('q3', models.CharField(default='', max_length=100, verbose_name='¿A qué edad tuvo su primer trabajo? ¿ Cuándo se volvió económicamente independiente?')),
                ('q4', models.CharField(default='', max_length=100, verbose_name='¿En que tipo de actividades le gusta tomar parte cuando no está trabajando? ¿Es usted miembro o líder de algún grupo?')),
                ('q5', models.CharField(default='', max_length=100, verbose_name='¿Qué tipo de lectura relacionada con el trabajo o recreativa le gusta?')),
                ('q6', models.CharField(default='', max_length=100, verbose_name='¿Prefiere usted trabajar sola o en grupos?')),
                ('q7', models.CharField(default='', max_length=100, verbose_name='¿Qué tipos de presiones de trabajo le gustan o le disgustan mas?')),
                ('q8', models.CharField(default='', max_length=100, verbose_name='¿En que formas es usted más eficaz trabajando con otros? ¿Menos eficaz?')),
                ('q9', models.CharField(default='', max_length=100, verbose_name='¿Que mejoras o nuevas ideas han sugerido en trabajos anteriores? ')),
                ('q10', models.CharField(default='', max_length=100, verbose_name='¿Cómo cree que lo describirían sus compañeros o sus subordinados?')),
                ('q11', models.CharField(default='', max_length=100, verbose_name='¿En que trabajo ha estado mas contento y por que? ¿Más descontento y porque?')),
                ('q12', models.CharField(default='', max_length=100, verbose_name='¿Qué cualidades le gusta mas en un superior? ¿Menos?')),
                ('q13', models.CharField(default='', max_length=100, verbose_name='¿Por qué asistió (o no) a la universidad? ')),
                ('q14', models.CharField(default='', max_length=100, verbose_name='Si tuviera la oportunidad de volver a cursar sus estudios, ¿qué haría diferente? ¿Por que?')),
                ('q15', models.CharField(default='', max_length=100, verbose_name='¿Cómo es similar y como es diferente a sus padres?')),
                ('q16', models.CharField(default='', max_length=100, verbose_name='¿Ha tenido de acumular una reserva financiera (ahorros, seguro de vida, etc.)?')),
                ('aceptar_condiciones', models.BooleanField(default=False, help_text='. Acepte los terminos y condiciones establecidas en la declaracion de Revergy Mexico para el tratamiento de todo la informacion proporcionada.', verbose_name='Aceptar Terminos Condiciones y privacidad de informacion')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('entrevista', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.entrevista')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_cliente',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('parque', models.CharField(max_length=100)),
                ('cliente', models.CharField(default='', max_length=80)),
                ('actividad', models.CharField(choices=[('Operacion y Mantenimiento', 'Operacion y Mantenimiento'), ('INSPECCION', 'INSPECCION'), ('SUBESTACION', 'SUBESTACION')], default='Operacion y Mantenimiento', max_length=80)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('analitica', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rh.analitica')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('clave_personal', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('alta_imss', models.DateField(null=b'I01\n', verbose_name='Fecha de alta IMSS')),
                ('RFC', models.CharField(max_length=30, null=b'I01\n')),
                ('NSS', models.CharField(max_length=30, null=b'I01\n')),
                ('CURP', models.CharField(max_length=30, null=b'I01\n')),
                ('email_personal', models.EmailField(blank=b'I01\n', max_length=50, null=b'I01\n', verbose_name='Email personal')),
                ('email_empresa', models.EmailField(blank=b'I01\n', max_length=50, null=b'I01\n', verbose_name='Email empresa')),
                ('telefono_personal', models.CharField(blank=b'I01\n', max_length=15, null=b'I01\n')),
                ('telefono_empresa', models.CharField(blank=b'I01\n', max_length=15, null=b'I01\n')),
                ('estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Union libre', 'Union libre')], default='Soltero(a)', max_length=50, null=b'I01\n', verbose_name='Estado civil')),
                ('case_emergency', models.CharField(max_length=100, null=b'I01\n', verbose_name='En caso de emergencia')),
                ('contact_emergency', models.CharField(max_length=15, null=b'I01\n', verbose_name='Contacto de emergencia')),
                ('tipo_sangre', models.CharField(choices=[('A positivo (A +)', 'A positivo (A +)'), ('A negativo (A-)', 'A negativo (A-)'), ('B positivo (B +)', 'B positivo (B +)'), ('negativo (B-)', 'negativo (B-)'), ('AB positivo (AB+)', 'AB positivo (AB+)'), ('AB negativo (AB-)', 'AB negativo (AB-)'), ('O positivo (O+)', 'O positivo (O+)'), ('O negativo (O-)', 'O negativo (O-)'), ('A Rh positivo', 'A Rh positivo'), ('A Rh negativo', 'A Rh negativo'), ('B Rh positivo', 'B Rh positivo'), ('B Rh negativo', 'B Rh negativo'), ('AB Rh positivo', 'AB Rh positivo')], default='A positivo (A +)', max_length=50, null=b'I01\n', verbose_name='Tipo de sangre')),
                ('domicilio', models.TextField(max_length=150, null=b'I01\n', verbose_name='Domicilio')),
                ('tipo_contrato', models.CharField(blank=b'I01\n', max_length=30, null=b'I01\n', verbose_name='Tipo de contrato')),
                ('duracion_contrato', models.CharField(blank=b'I01\n', max_length=15, null=b'I01\n', verbose_name='Tiempo de contrato')),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15, verbose_name='Estatus')),
                ('fk_analitica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.analitica', verbose_name='Analitica')),
                ('fk_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': ' Personal',
                'ordering': ['estatus'],
            },
        ),
        migrations.AddField(
            model_name='entrevista',
            name='responsable',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='rh.personal'),
        ),
        migrations.CreateModel(
            name='Asignacion_personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(choices=[('CAMPO', 'CAMPO'), ('OFICINA', 'OFICINA')], max_length=15)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.proyecto_cliente')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_vacante',
            fields=[
                ('clv_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('estatus', models.CharField(default='Pendiente', max_length=30)),
                ('fk_vacante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rh.vacante', verbose_name='Vacante')),
                ('fk_postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.postulante', verbose_name='Postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('even_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Evento')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('description', models.TextField(default='', max_length=200, null=True, verbose_name='Descripcion')),
                ('event_type', models.CharField(choices=[('ENTREVISTA', 'ENTREVISTA'), ('CARGA DE DOCUMENTO', 'CARGA DE DOCUMENTO'), ('', '')], default='ENTREVISTA', max_length=50, verbose_name='Tipo de evento')),
                ('postulante', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rh.postulante')),
            ],
        ),
        migrations.AddField(
            model_name='entrevista',
            name='postulante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rh.postulante'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('clv_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FORMACION', 'FORMACION'), ('EXP_LAB', 'EXPERIENCIA LABORAL'), ('CURP', 'CURP'), ('RFC', 'RFC'), ('ANEX', 'ANEXOS')], max_length=30)),
                ('descripcion', models.CharField(default='', help_text='Breve informacion acerca del reconocimiento abquirido', max_length=120, verbose_name='Descripcion')),
                ('archivo', models.FileField(help_text='Solo puede seleccionar archivos pdf', max_length=255, null=b'I01\n', upload_to=rh.models.upload_to, verbose_name='Archivo')),
                ('fecha_subida', models.DateField(auto_now=True)),
                ('fk_postulante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rh.postulante', verbose_name='Postulante')),
            ],
        ),
    ]
